### ISSUE TITLE
AccountDetailsPlus hides my account panel

### ISSUE THREAD

**Issue by jack652** [rauenzi/BetterDiscordAddons#600] opened 2022-05-08 00:00 UTC
**Which plugin/theme is this about?**
AccountDetailsPlus 

**Describe the Bug**
when AccountDetailsPlus is active, hides my account panel on the bottom next to the settings button

**To Reproduce**
have AccountDetailsPlus turned on

**Expected Behavior**
it should not hide the account pannel

**Screenshots**
![image](https://user-images.githubusercontent.com/48365199/167276019-cef7c363-c98e-4693-89a3-64d0521f0ff9.png)

**Discord Version**
stable

**Comment by TonyRL** [comment] 2022-05-08 19:41
Duplicate of #590

**Comment by rauenzi** [comment] 2022-08-30 11:23
This plugin has now been discontinued. Please see the README for information https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AccountDetailsPlus

**Closed by rauenzi** 2022-08-30 11:23 UTC
Labels: bug
