### ISSUE TITLE
[Bug] HideDisabledEmojis still not working

### ISSUE THREAD

**Issue by ant-killer** [rauenzi/BetterDiscordAddons#348] opened 2021-03-23 11:36 UTC
**Which plugin/theme is this about?**

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by SwiftWinds** [comment] 2021-03-30 08:28
duplicate of #344

**Comment by rauenzi** [comment] 2021-04-17 21:29
See above

**Closed by rauenzi** 2021-04-17 21:29 UTC
Labels: bug
