### ISSUE TITLE
[Bug] AccountDetails Plus - User Icon Disappears

### ISSUE THREAD

**Issue by Zhurama** [rauenzi/BetterDiscordAddons#586] opened 2022-04-18 22:27 UTC
**Which plugin/theme is this about?**
AccountDetailsPlus v1.0.1

**Describe the Bug**
User Area Icon and extra information disappears when plugin is active. Hover does not reveal.

**To Reproduce**
Reproduceable so long as plugin is active. If I turn off the ADP plugin everything shows; turn it on and the user icon vanishes with no right click functions to reveal or anything.

**Expected Behavior**
User Icon needs to show. There ought to be an option in the settings for autohide and hover as well.

**Screenshots**
Normal User Area

![Discord Normal User Area](https://user-images.githubusercontent.com/71163523/163885464-a10fa9fc-44e8-4363-a8b1-de57b8b145f3.jpg)

Account Details Plus Enabled - User Area
![Discord ADP Enabled User Area](https://user-images.githubusercontent.com/71163523/163885508-fd6699f2-07aa-4012-8398-2470324605c0.jpg)

**Discord Version**
Stable 124397 (2bf79b5)
BetterDiscord 1.5.3
Host 1.0.9004 Windows 10 64-Bit (10.0.19044)

**Additional Context**
Thank you for this plugin, and for your time and efforts on our behalf.. It has been indispensable. This problem only began to occur sd of the most recent updates..

Namaste...

Zhur.

**Comment by kobe9115** [comment] 2022-04-20 05:45
I too am having this issue, I was wondering for a while what caused it. Really quite frustrating.

**Comment by DraneLixX** [comment] 2022-04-21 16:28
Same Here

**Comment by Mister36MN** [comment] 2022-04-23 16:15
Can confirm - disabling plugin brought that space back to normal. Assuming it has something to do with the CSS/spacing caused by new updates, as there were some other plugins that have similar issues.

**Comment by Debuggerz1** [comment] 2022-04-25 02:17
Quick Fix: **This fix does not bring the whole functionally back to normal.** 

Previously you can left click and right click both the avatar and the username for the popout to show up.

This fix only works for the avatar, Discord seems to have changed a lot ? I tried to fix it for the username too but couldn't find a way as i'm not the original author and i don't know their though process of how they achieved this.

Still the fix is convenient enough to get the job done.

Line: 93

Old:
```
const popoutWrap = Utilities.getNestedProp(retAccount, "props.children.0.props");
```
New: 
```
const popoutWrap = Utilities.getNestedProp(retAccount, "props.children.0.props.children.0.props");
```

**Comment by TonyRL** [comment] 2022-04-25 20:53
Duplicate of #578

**Comment by NoFrans** [comment] 2022-05-15 01:02
> Quick Fix: **This fix does not bring the whole functionally back to normal.**
> 
> Previously you can left click and right click both the avatar and the username for the popout to show up.
> 
> This fix only works for the avatar, Discord seems to have changed a lot ? I tried to fix it for the username too but couldn't find a way as i'm not the original author and i don't know their though process of how they achieved this.
> 
> Still the fix is convenient enough to get the job done.
> 
> Line: 93
> 
> Old:
> 
> ```
> const popoutWrap = Utilities.getNestedProp(retAccount, "props.children.0.props");
> ```
> 
> New:
> 
> ```
> const popoutWrap = Utilities.getNestedProp(retAccount, "props.children.0.props.children.0.props");
> ```

Thank you very much. As for the nickname/name hover, just open the plugin in the editor and click "Save" so it unloads/loads the plugin and it "magically" works again. Don't know why, but that seems to be the fix for me.

**Comment by rauenzi** [comment] 2022-08-30 11:23
This plugin has now been discontinued. Please see the README for information https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AccountDetailsPlus

**Closed by rauenzi** 2022-08-30 11:23 UTC
Labels: bug
