### ISSUE TITLE
[Bug] Search Icon is Unalligned with Box

### ISSUE THREAD

**Issue by ZaneDragonBorn** [rauenzi/BetterDiscordAddons#433] opened 2021-07-05 16:30 UTC
**Which plugin/theme is this about?**
ServerSearch

**Describe the Bug**
The Search button has an Icon (Magnifier thing) that is in the wrong location. It's way too far to the Top-Left to where it looks strange (Not Centered) 

**To Reproduce**
1. Download Plugin
2. Enable it
3. Look at Button

**Expected Behavior**
It to be Centered in the Rounded Square.

**Screenshots**
![image](https://user-images.githubusercontent.com/68198648/124499809-a5197100-dd8c-11eb-9d23-b794cd14354c.png)

**Discord Version**
Stable

**Additional Context**
I don't have any Themes enabled. I only use Plugins (Nothing that affects this though). I do have the Server Discovery Menu that BD offers enabled though.

**Comment by dav1312** [comment] 2021-07-11 16:10
Duplicate of #390

**Closed** 2021-08-11 01:22 UTC
Labels: bug
