### ISSUE TITLE
[Bug] TextChannel & CategoryChannel Context Menu's not appearing

### ISSUE THREAD

**Issue by ghost** [rauenzi/BetterDiscordAddons#411] opened 2021-06-06 12:51 UTC
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
Context Menu for the TextChannel & CategoryChannel permissions is not appearing

**To Reproduce**
- Right-click a Text/CategoryChannel, and attempt to locate the **Permissions** tab.
- Does not appear

**Expected Behavior**
Upon right-clicking a Text/CategoryChannel, the **Permissions** tab should appear.

**Screenshots**
`w/ bug`
![image](https://user-images.githubusercontent.com/85442094/120924937-299ca500-c6a4-11eb-8c99-c5ccc2acfe8d.png)
`w/ fix`
![image](https://user-images.githubusercontent.com/85442094/120924946-3e793880-c6a4-11eb-9e2c-f81f0cadcc9c.png)

**Discord Version**
Ptb 86917

**Additional Context**
Created a [fork](https://github.com/csokolove/BetterDiscordAddons/blob/master/Plugins/PermissionsViewer/PermissionsViewer.plugin.js) w/ fix

**Comment by csokolove** [comment] 2021-06-06 15:46
**Manual fix until update pushed**

Replace;

```
const [, CategoryChannelContextMenu, TextChannelContextMenu] = WebpackModules.getModules(m => m.default && m.default.displayName == "ChannelListTextChannelContextMenu");
```
with
```
const [TextChannelContextMenu, CategoryChannelContextMenu] = WebpackModules.getModules(m => m.default && m.default.displayName == "ChannelListTextChannelContextMenu");

```

in the `PermissionsViewer.plugin.js` file.

**Comment by dav1312** [comment] 2021-06-07 14:14
Duplicate of #406 
Zere closed it for unknown reasons, the issue has not been fixed

**Comment by rauenzi** [comment] 2021-06-07 14:24
> 
> 
> Duplicate of #406
> Zere closed it for unknown reasons, the issue has not been fixed

Please reread my comment there and you will understand.

**Comment by csokolove** [comment] 2021-06-07 15:58
Got it. I'll close this issue, and use #406. Thanks

**Comment by rauenzi** [comment] 2021-06-07 15:59
No this is the one to use

**Comment by rauenzi** [comment] 2021-08-11 00:34
Fixed at latest level

**Closed by rauenzi** 2021-08-11 00:34 UTC
Labels: bug
