### ISSUE TITLE
PermissionsViewer [Bug] 

### ISSUE THREAD

**Issue by BlueStarBRS** [rauenzi/BetterDiscordAddons#365] opened 2021-04-09 11:52 UTC
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
permissions option on the right click missing on profile and in the chat

**Discord Version**
newest one app-1.0.9001

**Comment by rauenzi** [comment] 2021-04-17 21:31
Duplicate of #351

**Closed by rauenzi** 2021-04-17 21:31 UTC
Labels: bug

**Comment by BlueStarBRS** [comment] 2021-05-02 14:19
@rauenzi 
> Duplicate of #351

and still not working
![image](https://user-images.githubusercontent.com/25110093/116816441-389ead80-ab62-11eb-91f8-da3abe7c38d0.png)

**Comment by rauenzi** [comment] 2021-05-02 14:21
You already posted that on the other one.
