### ISSUE TITLE
[Bug] RoleMembers crashes discord.

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [rauenzi/BetterDiscordAddons#269] opened 2020-08-10 16:01 UTC
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
Clicking on someone inside of the popups will crash discord.

**To Reproduce**
Install the plugin, open up the thing in the server context menu, click a role then click on someone with that role.

**Expected Behavior**
Either the user's popout or something else is supposed to appear.

**Screenshots**
![Screenshot_846](https://user-images.githubusercontent.com/54776821/89803736-2475d480-db2b-11ea-82cb-5bf7613f1a6c.png)
![Screenshot_847](https://user-images.githubusercontent.com/54776821/89803740-250e6b00-db2b-11ea-9ba4-8587f4e7c7b4.png)

**Discord Version**
Stable

**Comment by Drflash55** [comment] 2020-08-15 05:10
Can confirm that this does indeed still happen.
![image](https://user-images.githubusercontent.com/13694448/90305783-11009b80-de94-11ea-8f6d-e77ee91d49e8.png)

Error that appears when Discord crashes.

**Comment by rauenzi** [comment] 2020-08-17 04:16
This has been fixed with the latest version of the library (there was an update just now). Please test with that and let me know!

**Comment by Drflash55** [comment] 2020-08-17 05:34
I have tested it out, and it now works as intended.

**Closed** 2020-08-17 17:38 UTC
Labels: bug
