### ISSUE TITLE
[Bug] AutoPlayGifs doesn't play server icons in collapsed folders.

### ISSUE THREAD

**Issue by EvelynProto** [rauenzi/BetterDiscordAddons#458] opened 2021-08-12 19:27 UTC
**Which plugin/theme is this about?**
AutoPlayGifs

**Describe the Bug**
AutoPlayGifs doesn't play server GIFs if the server is in a collapsed folder.

**To Reproduce**
Place a folder with a GIF icon into a folder

**Expected Behavior**
The server's icon plays

**Screenshots**
![broken](https://user-images.githubusercontent.com/54776821/129257058-3c187378-e070-463e-ae5a-5e376c85cadc.gif)

**Discord Version**
Stable 93253

**Comment by rauenzi** [comment] 2021-08-12 20:16
This is a duplicate of #327

**Closed by rauenzi** 2021-08-12 20:16 UTC
Labels: bug
