### ISSUE TITLE
[Bug] [StatusEverywhere] Crash on opening user info

### ISSUE THREAD

**Issue by DarkEnchanter1** [rauenzi/BetterDiscordAddons#268] opened 2020-08-08 04:07 UTC
**Which plugin/theme is this about?**
StatusEverywhere

**Describe the Bug**
Upon clicking a user's profile picture to bring up their user info, discord will either crash or occasionally open the panel in the top left corner instead.

**To Reproduce**
Open any channel and click a user's profile; Discord will crash.

**Expected Behavior**
...not to crash?

**Discord Version**
Stable

**Comment by SoopaKhell** [comment] 2020-08-08 20:57
I was able to reproduce this.

The full javascript error looks like this:
```
e5c803440ee725aeda60.js:74 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Bu (e5c803440ee725aeda60.js:74)
    at e5c803440ee725aeda60.js:74
    at Wa (e5c803440ee725aeda60.js:74)
    at Rs (e5c803440ee725aeda60.js:74)
    at Au (e5c803440ee725aeda60.js:74)
    at Iu (e5c803440ee725aeda60.js:74)
    at cu (e5c803440ee725aeda60.js:74)
    at e5c803440ee725aeda60.js:74
    at t.unstable_runWithPriority (e5c803440ee725aeda60.js:82)
    at Xo (e5c803440ee725aeda60.js:74)
    at $o (e5c803440ee725aeda60.js:74)
    at Jo (e5c803440ee725aeda60.js:74)
    at fu (e5c803440ee725aeda60.js:74)
    at Rn (e5c803440ee725aeda60.js:74)
    at HTMLDocument.r (14b30977c7e9f47adb22.js:16)```

Following the link to the react website, we get this:
```Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.```

**Comment by MrMoizt** [comment] 2020-08-09 21:25
How do you fix this?

**Comment by SoopaKhell** [comment] 2020-08-10 22:41
@MrMoizt I'm just going to wait for someone else to lol
I don't understand how plugins work

**Comment by TheRealGeDev** [comment] 2020-08-12 19:14
I got the same problem today.  I never got it before. btw The crash easter egg of betterdiscord is really fun, you guys should go check it out

**Comment by rauenzi** [comment] 2020-08-17 04:16
This has been fixed with the latest version of the library (there was an update just now). Please test with that and let me know!

**Comment by Antideveloppeur** [comment] 2020-08-17 13:29
I can confirm that it is fixed

**Closed** 2020-08-17 17:38 UTC
Labels: bug, confirmed
