### ISSUE TITLE
[Bug] "StatusEverywhere" not working.

### ISSUE THREAD

**Issue by BlackLightX** [rauenzi/BetterDiscordAddons#385] opened 2021-05-02 19:17 UTC
**Which plugin/theme is this about?**
StatusEverywhere

**Describe the Bug**
Nothing happens. The plugin does not work.

**To Reproduce**
When you download the plugin, you will see that it does not work.

**Expected Behavior**
I want Discord to add user status wherever it doesn't.

**Screenshots**
![Screenshot_10](https://user-images.githubusercontent.com/65299525/116824508-46b8f200-ab93-11eb-9c48-c16592f8e708.jpg)
![Screenshot_11](https://user-images.githubusercontent.com/65299525/116824509-47518880-ab93-11eb-87d5-335ba4475d77.jpg)

**Discord Version**
Stable 83364 (9af39da)
BetterDiscord 1.1.0
Host 1.0.9001
Windows 10 64-Bit (10.0.19042)

**Additional Context**
I do not use a theme. I deleted and reinstalled the plugin, it didn't work. I disabled all plugins and tried it, it didn't work. I think this issue is related to the plugin and needs an update.

**Comment by rauenzi** [comment] 2021-05-06 23:01
This is a duplicate of #366

**Closed by rauenzi** 2021-05-06 23:01 UTC
Labels: bug
