### ISSUE TITLE
[Bug] EmojiUtilities context menu issues

### ISSUE THREAD

**Issue by JohnWeak1** [rauenzi/BetterDiscordAddons#263] opened 2020-07-27 17:08 UTC
**Which plugin/theme is this about?**
EmojiUtilities

**Describe the Bug**
right-clicking on an emote in the emote menu bugs out the context menu and can't be interacted with
therefore not being able to (un)favorite or (un)blacklist emotes in the emote menu

**To Reproduce**
right-click an emote in the emote menu and left-click an option in the context menu

**Expected Behavior**
being able to interact with the context menu in the emote menu

**Screenshots**
![image](https://user-images.githubusercontent.com/42245432/88570410-4efc6380-d03c-11ea-9db4-03d790486e7b.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment] 2020-07-27 17:12
I just pushed out an update for the library, please update that and reload Discord and see if the issue persists. The EmojiPicker will close (expected) but the context menu should be usable.

**Comment by MarioLowee** [comment] 2020-08-02 10:36
Seems to be a duplicate of #239 (Witch if that the case then it's fixed)

**Closed** 2020-08-17 04:04 UTC
Labels: awaiting response, bug
