### ISSUE TITLE
[Bug] BetterRoleColors doesn't work with new highlighted mentions. 

### ISSUE THREAD

**Issue by Jekyde412** [rauenzi/BetterDiscordAddons#398] opened 2021-05-21 22:06 UTC
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
As of the last update where Discord added a highlight to the mentions. 

**To Reproduce**
@ someone

**Expected Behavior**
I expected the person I mentioned would have the same color as their role. 

**Screenshots**
![1](https://user-images.githubusercontent.com/84545045/119202640-118f1980-ba46-11eb-9cd6-76006ef189dc.JPG)
![2](https://user-images.githubusercontent.com/84545045/119202641-1227b000-ba46-11eb-8683-e0d6ee1eb792.JPG)

**Discord Version**
Stable

**Additional Context**
It was working until the last update to the mentions, or to the discord logo; I can't remember when I last saw it working, but I do know it was definitely working before the names got changed.

**Comment by rauenzi** [comment] 2021-06-05 17:16
Duplicate of #397

**Closed by rauenzi** 2021-06-05 17:16 UTC
Labels: bug
