### ISSUE TITLE
[Bug] EmojiUtilities bug

### ISSUE THREAD

**Issue by Narko4tacey** [rauenzi/BetterDiscordAddons#246] opened 2020-06-20 22:35 UTC
**Which plugin/theme is this about?**

EmojiUtilities
**Describe the Bug**

When i click on Favorite Emoji it closes the emoji menu and doesn't add emoji to favorite
**To Reproduce**

**Expected Behavior**

**Screenshots**

https://gyazo.com/34af25eef8a1f7283b5f44160f38eb8c
**Discord Version**

**Additional Context**

**Comment by Glaived** [comment] 2020-06-22 12:18
**Discord Version**
Stable

**Comment by rauenzi** [comment] 2020-06-24 00:28
Duplicate of #239

**Closed by rauenzi** 2020-06-24 00:28 UTC
Labels: bug
