### ISSUE TITLE
BetterFormattingRedux not working as intended.

### ISSUE THREAD

**Issue by roydhritiman** [rauenzi/BetterDiscordAddons#448] opened 2021-07-31 16:43 UTC
Hi, I downloaded the plugin via BetterDiscord, but it doesn't seem to function as shown in the preview. I'm not able to highlight and format text. 

Providing a GIF to show the exact issue below. Please help me out! :)

Thanks!

![T83ZPPr7Ce](https://user-images.githubusercontent.com/38285763/127746626-a7252aa7-2c14-45b2-8928-53f0335f73df.gif)

**Comment by Z1wolfmaster1** [comment] 2021-07-31 18:08
Same here

**Comment by CarsterX** [comment] 2021-07-31 23:40
Same

**Comment by rauenzi** [comment] 2021-08-01 00:00
Comments like this are not helpful. In the future just add :+1: to the original issue.

**Comment by rauenzi** [comment] 2021-08-10 22:20
Duplicate of #443

**Closed by rauenzi** 2021-08-10 22:20 UTC
