### ISSUE TITLE
[Feature] Missing new "quote" format (>)

### ISSUE THREAD

**Issue by OneklickLP** [rauenzi/BetterDiscordAddons#153] opened 2019-08-16 23:19 UTC
**BetterFormatingRedux by Zerebos**

**Missing new "quote" format.**

**by tipping a ">" before your meassge, for example with " > please add this" Discord is formatting the whole sentence like shown below. Its new, i would really like to see that function in BetterFormatingRedux**

**![image](https://user-images.githubusercontent.com/35150123/63202924-7dcc3480-c08c-11e9-9b0c-bb79d231e0e1.png) 
![image](https://user-images.githubusercontent.com/35150123/63202946-9e948a00-c08c-11e9-9ca0-2d627afddd85.png)**

**Comment by rauenzi** [comment] 2019-09-06 22:19
Unfortunately this will take some time as the way BFRedux was originally written was... bad... So I'll have to rewrite it to support stuff that doesn't use the same character on both sides of the text.

**Comment by rauenzi** [comment] 2019-09-06 22:20
Actually this is a duplicate of #151

**Closed by rauenzi** 2019-09-06 22:20 UTC
Labels: enhancement
