### ISSUE TITLE
RemoveMinimumSize Plugin [Bug] 

### ISSUE THREAD

**Issue by BlueStarBRS** [rauenzi/BetterDiscordAddons#364] opened 2021-04-09 11:38 UTC
**Which plugin/theme is this about?**
RemoveMinimumSize

**Describe the Bug**
with the new BDiscord Update its dont work anymore see error on screenshot

**To Reproduce**
just try to load it

**Expected Behavior**
it loads and work ?

**Screenshots**
![image](https://user-images.githubusercontent.com/25110093/114174158-88f66700-9938-11eb-9865-e59f7b000426.png)

**Discord Version**
app-1.0.9001 newest one and the new BDiscord version

**Comment by rauenzi** [comment] 2021-04-17 21:31
Duplicate of #357

**Closed by rauenzi** 2021-04-17 21:31 UTC
Labels: bug
