### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Justman10000** [rauenzi/BetterDiscordAddons#469] opened 2021-09-24 03:57 UTC
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
You are no longer able to display the members of the individual roles

**To Reproduce**
Go to Role Members and click on a role, nothing more happens

**Expected Behavior**
Usually the members of the respective role are displayed when you click on a role...

**Screenshots**
![grafik](https://user-images.githubusercontent.com/49990629/134615834-6aa0aa5c-8326-4abd-9a85-f70b13127c34.png)
![grafik](https://user-images.githubusercontent.com/49990629/134615837-d9e6181f-75a4-4118-bd3a-b1b2856a3d56.png)

**Discord Version**
Stable, latest

**Additional Context**
_Previous data is sufficient_

**Comment by acendvgnt** [comment] 2021-09-24 09:14
duplicate of #462 ?

**Comment by Justman10000** [comment] 2021-09-24 20:15
> 
> 
> duplicate of #462 ?

Overlooked, but please fix...

**Closed** 2021-09-24 20:17 UTC
Labels: bug
