### ISSUE TITLE
[Bug] [AccountDetailsPlus]

### ISSUE THREAD

**Issue by thegamerx1** [rauenzi/BetterDiscordAddons#167] opened 2019-09-21 17:27 UTC
https://youtu.be/7TWQPJIJnzU

**Comment by rauenzi** [comment] 2019-09-21 17:31
Does not follow bug template format nor really have any explanation other than a video I can't be bothered to watch. Duplicate of #160

**Closed by rauenzi** 2019-09-21 17:31 UTC
Labels: bug
