### ISSUE TITLE
[Bug] BetterFormattingRedux v2.3.11 dont work

### ISSUE THREAD

**Issue by BlueStarBRS** [rauenzi/BetterDiscordAddons#445] opened 2021-07-27 11:37 UTC
**Which plugin/theme is this about?**
Better Formatting Redux
**v2.3.11**

**Describe the Bug**
if you press some of this buttons to transform the text nothing happpens it just unmarks the text not more.

**screenshots**
![image](https://user-images.githubusercontent.com/25110093/127147175-722c9c64-a417-48f6-bbc9-5c72792e2795.png)

**To Reproduce**
try to transform a text

**Discord Version**
**1.0.9002**

**Comment by tameTNT** [comment] 2021-07-27 16:44
This is a duplicate of #443

**Comment by rauenzi** [comment] 2021-08-10 22:21
See above

**Closed by rauenzi** 2021-08-10 22:21 UTC
Labels: bug
