### ISSUE TITLE
[Bug] PLUGIN/STATUSEVERYWERE

### ISSUE THREAD

**Issue by nexioss** [rauenzi/BetterDiscordAddons#425] opened 2021-06-26 19:55 UTC
**Describe the Bug**
dont work at all.

**To Reproduce**
just installe the plugin and acivate it.

**Expected Behavior**
adding the statue directly on the chat.

**Screenshots**
![Capturnge](https://user-images.githubusercontent.com/86494178/123524236-1f7d2d80-d6c9-11eb-8cd1-1900863944bf.PNG)

**Discord Version**
Stable 88806 (ec5c1a3)

**Additional Context**
none

**Comment by dav1312** [comment] 2021-06-27 15:36
Duplicate of #366

**Comment by rauenzi** [comment] 2021-08-10 21:46
See above

**Closed by rauenzi** 2021-08-10 21:46 UTC
Labels: bug
