### ISSUE TITLE
[Bug] [BetterRoleColors] Colorising User Mentions in chat doesn't work

### ISSUE THREAD

**Issue by Thedoczek** [rauenzi/BetterDiscordAddons#416] opened 2021-06-08 16:59 UTC
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Self-explaination

**To Reproduce**
Just turn this one on
![obraz](https://user-images.githubusercontent.com/69758777/121227178-93c36e80-c88b-11eb-81aa-c12d1ce90369.png)

**Expected Behavior**
I wanted it to color

**Screenshots**
![obraz](https://user-images.githubusercontent.com/69758777/121227057-768ea000-c88b-11eb-8d80-8a89cd34dcaa.png)

**Discord Version**
Newest stable

**Comment by rauenzi** [comment] 2021-06-08 17:19
Duplicate of #397

**Closed by rauenzi** 2021-06-08 17:19 UTC
Labels: bug
