### ISSUE TITLE
[Bug]  With removing avatar at AccountDetailsPlus

### ISSUE THREAD

**Issue by AjaxTheLord** [rauenzi/BetterDiscordAddons#590] opened 2022-04-24 13:12 UTC
**Which plugin/theme is this about?**
AccountDetailsPlus by Zack

**Describe the Bug**
When i activate plugin my avatar removes (or hide) i checked  if another plugins  making this issue but they're not so it's error somewhere in code

**To Reproduce**
Idk

**Expected Behavior**
As well It's work how expected but I just click on chat avatar (or right button click on setting icon)

**Screenshots**
![screenshot 2022-04-24 161104](https://user-images.githubusercontent.com/103654434/164978186-b11cb45e-1fd0-4fb4-9362-fbe59e335ef5.png)

**Discord Version**
last version

**Additional Context**
idk

**Comment by TonyRL** [comment] 2022-04-25 20:53
Duplicate of #586

**Comment by rauenzi** [comment] 2022-08-30 11:23
This plugin has now been discontinued. Please see the README for information https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/AccountDetailsPlus

**Closed by rauenzi** 2022-08-30 11:23 UTC
Labels: bug
