### ISSUE TITLE
[Bug] Plugins fails to load

### ISSUE THREAD

**Issue by TurboBiscuit** [rauenzi/BetterDiscordAddons#163] opened 2019-09-15 03:21 UTC
**Which plugin/theme is this about?**
Account Details Plus

**Describe the Bug**
When loading the plugin the "Content Errors" page opens with this message:
https://imgur.com/a/UbG6qOq

**To Reproduce**
Load the plugin

**Expected Behavior**
Loads the plugin with no issues

**Screenshots**
https://imgur.com/a/oNNifua

**Discord Version**
PBT

**Additional Context**
None

**Comment by rauenzi** [comment] 2019-09-21 14:56
Duplicate of #160

**Closed by rauenzi** 2019-09-21 14:56 UTC
Labels: bug
