### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NishantMajumdar** [rauenzi/BetterDiscordAddons#405] opened 2021-05-30 16:50 UTC
**Which plugin/theme is this about?**

Idk, betterdiscord itself maybe
**Describe the Bug**

I use Discord. It works ok for like 1minute and then it crashes, and shows that it died on level9000 (clearVision), if i disable the theme, it shows the regular Discord Crash screen.
**To Reproduce**

Nothing, just use the app for 1m and then crash
**Expected Behavior**

Not to crash
**Screenshots**

Inspect Error: 
e7b7db3d23214310c8f8.js:2 TypeError: Cannot read property 'startsWith' of undefined
    at AvatarComponent.render (<anonymous>:86:37)
    at $a (2c642b44e59d54018b37.js:2)
    at Ja (2c642b44e59d54018b37.js:2)
    at Cs (2c642b44e59d54018b37.js:2)
    at Au (2c642b44e59d54018b37.js:2)
    at Iu (2c642b44e59d54018b37.js:2)
    at cu (2c642b44e59d54018b37.js:2)
    at 2c642b44e59d54018b37.js:2
    at t.unstable_runWithPriority (2c642b44e59d54018b37.js:2)
    at zi (2c642b44e59d54018b37.js:2)
    at Ji (2c642b44e59d54018b37.js:2)
    at Qi (2c642b44e59d54018b37.js:2)
    at du (2c642b44e59d54018b37.js:2)
    at Function.t.emitChanges (2c642b44e59d54018b37.js:2)
    at e.t._dispatch (2c642b44e59d54018b37.js:2)
    at e.t.dispatch (2c642b44e59d54018b37.js:2)
    at MessageLoggerV2.onDispatchEvent (<anonymous>:2469:218)
    at Object.callback (<anonymous>:662:37)
    at e.dispatch (<anonymous>:1908:57)
    at s.<anonymous> (2c642b44e59d54018b37.js:2)
    at s.emit (2c642b44e59d54018b37.js:2)
    at s.u._handleDispatch (2c642b44e59d54018b37.js:2)
    at r (2c642b44e59d54018b37.js:2)
    at r._onDataReady (2c642b44e59d54018b37.js:2)
    at r.t.handleFlushEnd (2c642b44e59d54018b37.js:2)
    at d.push (2c642b44e59d54018b37.js:2)
    at r.t.feed (2c642b44e59d54018b37.js:2)
    at WebSocket.<anonymous> (2c642b44e59d54018b37.js:2)

**Discord Version**

Stable latest
**Additional Context**

Please fix this soon.

**Comment by rauenzi** [comment] 2021-06-05 17:28
Duplicate of #366

**Closed by rauenzi** 2021-06-05 17:28 UTC
Labels: bug
