### ISSUE TITLE
[Feature] Role Members

### ISSUE THREAD

**Issue by siltentassasin** [rauenzi/BetterDiscordAddons#389] opened 2021-05-09 12:32 UTC
Is it possible to make, that the role members plugin can open the role users list, if you click on the role mention? Not only in the server context menu.

And I think an option to disable it in the server context menu would also be great, because I e.g. would prefer if it is just by the role mentions and only optional in the context menu

**Comment by vovklosev** [comment] 2021-05-12 15:18
Discord stopped working after updating.

**Comment by rauenzi** [comment] 2021-06-05 17:19
Duplicate of #281

**Closed by rauenzi** 2021-06-05 17:19 UTC
Labels: enhancement
