### ISSUE TITLE
Mentions are not correctly colored in BetterRoleColors [Bug] 

### ISSUE THREAD

**Issue by ArcWand06** [rauenzi/BetterDiscordAddons#403] opened 2021-05-29 19:05 UTC
**Which plugin/theme is this about?**
BetterRoleColors v0.8.14

**Describe the Bug**
Mentions in chat are not colored according to role color.

**To Reproduce**
Turn the plugin on, and send a `@` ping to someone in the server.

**Expected Behavior**
The ping should be colored by role. In the attached screenshot, the first ping should be light cyan, while the second should be green-ish. However, they are both just the default colorr.

**Screenshots**
![image](https://user-images.githubusercontent.com/57409597/120082045-b46f1580-c08e-11eb-86dc-89404168b7c4.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment] 2021-06-05 17:16
Duplicate of #397

**Closed by rauenzi** 2021-06-05 17:16 UTC
Labels: bug
