### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by itaintraf** [rauenzi/BetterDiscordAddons#309] opened 2020-11-27 09:23 UTC
**Which plugin/theme is this about?**
BetterFormattingRedux

**Describe the Bug**
On click of formatting option, nothing is produced

**To Reproduce**
Click on any of the formatting options

**Expected Behavior**
Text should be surrounded with the respective formatting option

**Discord Version**
Stable

**Comment by rauenzi** [comment] 2020-12-03 19:08
Duplicate of #311 (duping forward due to convo)

**Closed by rauenzi** 2020-12-03 19:08 UTC
Labels: bug
