### ISSUE TITLE
[Other] BetterRoleColors - coloring a ping inside a text

### ISSUE THREAD

**Issue by Poirot12345T** [rauenzi/BetterDiscordAddons#413] opened 2021-06-07 16:04 UTC
Ho, when I first installed the plugin, it made even pings in the text, right now it doesn't (I'm not the only one using this plugin and my teammate has the same issues that pings to people are not colored). Other things work properly (checked if it is not a problem of a used theme, and it seems that it is not).
Would it be possible to get this coloring back? Thank you so much!

**Comment by rauenzi** [comment] 2021-06-07 16:10
Duplicate of #397

**Closed by rauenzi** 2021-06-07 16:10 UTC
