### ISSUE TITLE
[Bug] Formatting Redux doesn't work at all

### ISSUE THREAD

**Issue by LillyWho** [rauenzi/BetterDiscordAddons#198] opened 2019-12-13 17:36 UTC
**Which plugin/theme is this about?**
Formatting Redux

**Describe the Bug**
Text isn't being converted via manual tagging. Clicking on formatting options in the toolbar doesn't add formatting symbols.

**To Reproduce**
Bug description says it all I think.

**Expected Behavior**
Working formatting via the symbols set in the settings, and a toolbar that inserts them into the chat box.

**Discord Version**
Stable

**Comment by williamjcm** [comment] 2019-12-13 17:39
The plugin wasn't updated for the new WYSIWYG chatbox.

**Comment by Huddlect** [comment] 2019-12-17 17:51
Isn't that a duplicate of #195 ?

**Comment by marcocorriero** [comment] 2019-12-22 12:00
Same, can someone fix it? Since i used it all the time?

**Comment by rauenzi** [comment] 2019-12-22 13:25
Yes this is a duplicate, and it will be fixed when I have time. Please be patient.

**Closed by rauenzi** 2019-12-22 13:25 UTC
Labels: bug
