### ISSUE TITLE
[Bug] BetterRoleColors crashed

### ISSUE THREAD

**Issue by Osyruu** [rauenzi/BetterDiscordAddons#170] opened 2019-09-25 14:39 UTC
Hey, when I load the BRC plugin it's crashed and send me in the console this : http://prntscr.com/paubku and unload some plugins automatically : http://prntscr.com/paudnm
Or maybe this could help you to fix it : http://prntscr.com/paufuh

**Comment by rauenzi** [comment] 2019-09-25 14:41
Duplicate of #169

**Closed by rauenzi** 2019-09-25 14:41 UTC
Labels: bug
