### ISSUE TITLE
[Bug] PermissionsViewer don't show user's permissions in popout

### ISSUE THREAD

**Issue by Traktool** [rauenzi/BetterDiscordAddons#580] opened 2022-04-10 10:45 UTC
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
The plugin don't show the user's permissions in the user popout
I've tried to disable all plugins (except libs and PermissionsViewer), restart Discord, but nothing

**To Reproduce**
Install the plugin and open any user popout

**Expected Behavior**

**Screenshots**

**Discord Version**
Discord Stable 123305
BetterDiscord 1.5.2

**Additional Context**

**Comment by Bobobaal** [comment] 2022-04-13 20:08
It's not a bug and not even a feature of the plugin.
It clearly states RoleMembers' only function is to show which members belong to a specific role.
If you really want to see a specific user's permissions the plugin you need is PermissionsViewer.
![image](https://user-images.githubusercontent.com/15947020/163261760-02e92901-b1bf-44e0-9f25-65c2880d1db9.png)

**Comment by Traktool** [comment] 2022-04-17 17:06
My bad, I've wrote this ticket for PermissionsViewer, but change it to RoleMembers, I don't know why xD
But yeah, I'm talking about PermissionsViewer

**Comment by GoldenWolfBW** [comment] 2022-04-24 23:16
I figured it out, it's a bug when using BetterRoleColors

**Comment by rauenzi** [comment] 2022-08-30 04:36
This has been fixed in the latest version!

**Closed by rauenzi** 2022-08-30 04:36 UTC
Labels: bug
