### ISSUE TITLE
[Bug] Permissions Viewer - Show In Popouts

### ISSUE THREAD

**Issue by MuhaGX** [rauenzi/BetterDiscordAddons#432] opened 2021-07-05 12:26 UTC
**Which plugin/theme is this about?**

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Additional Context**

**Comment by MuhaGX** [comment] 2021-07-05 12:27
![image](https://user-images.githubusercontent.com/70599137/124471416-08c09000-ddc7-11eb-92a2-73f13a8afc8c.png)

**Comment by MuhaGX** [comment] 2021-07-05 12:28
Why is the role permission not showing

**Comment by MuhaGX** [comment] 2021-07-05 12:29
Why is the role permission not showing?

**Comment by dav1312** [comment] 2021-07-07 12:44
Duplicate of #424

**Closed** 2021-08-10 23:40 UTC
Labels: bug
