### ISSUE TITLE
[Bug] Disappears after restarting discord

### ISSUE THREAD

**Issue by lololol69420** [rauenzi/BetterDiscordAddons#277] opened 2020-08-22 21:28 UTC
If i restart discord it disappears on the spot, like it isn't there anymore, so i have to go back to plugins and turn it back off and on to get it back.

**Comment by rauenzi** [comment] 2020-09-19 20:33
What is this in reference to?

**Comment by lololol69420** [comment] 2020-09-19 20:42
Server search

**Comment by rauenzi** [comment] 2020-09-19 20:45
This is a duplicate of #275

**Closed by rauenzi** 2020-09-19 20:45 UTC
Labels: awaiting response, bug, needs info
