### ISSUE TITLE
The plugin doesn't work (BetterFormattingRedux)

### ISSUE THREAD

**Issue by JustASimpleeGuy** [rauenzi/BetterDiscordAddons#596] opened 2022-05-02 14:44 UTC
The plugin start normally, but the buttons doesn't work. I deleted the configs and restarted the Better Discord, and nothing.

**Comment by xsmashx88x** [comment] 2022-05-03 17:48
same issue for me as well

**Comment by Technetium1** [comment] 2022-05-20 11:22
Duplicate of https://github.com/rauenzi/BetterDiscordAddons/issues/576

**Comment by rauenzi** [comment] 2022-08-30 05:20
This has been fixed with the latest update!

**Closed by rauenzi** 2022-08-30 05:20 UTC
Labels: bug
