### ISSUE TITLE
having crash issues with better role color

### ISSUE THREAD

**Issue by Harlecorn** [rauenzi/BetterDiscordAddons#171] opened 2019-09-25 15:40 UTC
Randomly crashed discord, after being up for several hours, and upon restart, it started giving me this error:
https://gyazo.com/f6b40335264a75482cf2aa985626cd89
tried uninstalling/reinstalling discord, bandage discord, the plugins, and it's only BRC that's still crashing (and causing others that are loading after it to crash). The library that's required is loading and working fine (also redownloaded and updated that just in case).

Also note, the invite for discord server is no longer valid.

**Comment by rauenzi** [comment] 2019-09-25 15:53
Not using an issue template and duplicate of #169

**Closed by rauenzi** 2019-09-25 15:53 UTC
