### ISSUE TITLE
[Bug] Doesn't Works

### ISSUE THREAD

**Issue by Jakemessi** [rauenzi/BetterDiscordAddons#307] opened 2020-11-26 18:14 UTC
**Which plugin/theme is this about?**
Better Formating Redux

**Describe the Bug**
It doesn't work I click on one of the options and nothing happens

**To Reproduce**
Click on one of the ways to format the writing

**Expected Behavior**
.... Format the text
**Screenshots**

**Discord Version**
stable

**Additional Context**

**Comment by rauenzi** [comment] 2020-12-03 19:25
Duplicate of #311

**Closed by rauenzi** 2020-12-03 19:25 UTC
Labels: bug
