### ISSUE TITLE
Mentions coloring not working

### ISSUE THREAD

**Issue by DanRocs298** [rauenzi/BetterDiscordAddons#126] opened 2019-05-27 21:51 UTC
Hello. I recently updated the plugin to the latest version, and now for some reason, the mentions coloring doesn't work anymore.. Its supposed to be red, but its not...

![image](https://user-images.githubusercontent.com/6370453/58440422-eb794d80-80a7-11e9-8dcf-cf83764563d6.png)

![image](https://user-images.githubusercontent.com/6370453/58440425-f0d69800-80a7-11e9-9ff4-75ceca608c0f.png)

As you can see it is blue, when with the plugin, its supposed to be red when I get mentioned.

**Comment by rauenzi** [comment] 2019-05-27 21:56
Next time please search existing issues to avoid making duplicates. This is a duplicate of #121

**Closed by rauenzi** 2019-05-27 21:56 UTC
