### ISSUE TITLE
ZereBos Plugins[Bug] 

### ISSUE THREAD

**Issue by Bluy6444** [rauenzi/BetterDiscordAddons#368] opened 2021-04-12 08:28 UTC
**Which plugin/theme is this about?**

### Either Zerebos ZeresPluginLibrary or BetterRoleColors isn't working.
**Describe the Bug**

Better Roles Color not showing colors for the first role in VCs or at the bottom. the main reason being that if you use OwnerTag plugin and BetterRolesColor it doesn't let better roles color work as intended. and i checked by enabling both plugins, and then only enabling better roles color plugin. as you can see in the screenshots. also the name at the bottom doesn't work either way.
**To Reproduce**

**Expected Behavior**

Better roles color used to display role color in VCs and at the bottom.
**Screenshots**

![Discord_Mty6tOQyxw](https://user-images.githubusercontent.com/25245017/114364225-da456700-9b81-11eb-9471-2c4723389c07.png)
![Discord_zB5fisSsAm](https://user-images.githubusercontent.com/25245017/114364345-f9dc8f80-9b81-11eb-9b7b-5c6cd912f399.png)
![Discord_z3q5OhVg71](https://user-images.githubusercontent.com/25245017/114364353-fba65300-9b81-11eb-8042-41d498a13f1f.png)
![Discord_JTk2q5x7yQ](https://user-images.githubusercontent.com/25245017/114364356-fba65300-9b81-11eb-8d84-366d6926689a.png)

**Discord Version**

Stable 81972 (9bccc1c) / BD 1.0.0 (stable)
**Additional Context**

**Comment by rauenzi** [comment] 2021-04-17 21:32
Duplicate of #353

**Closed by rauenzi** 2021-04-17 21:32 UTC
Labels: bug
