### ISSUE TITLE
Is the DoNotTrack plugin updated

### ISSUE THREAD

**Issue by Latrolage** [rauenzi/BetterDiscordAddons#359] opened 2021-04-06 04:08 UTC
Is the DoNotTrack plugin still up to date. As far as I can tell, it doesn't really do anything, unless im misunderstanding what it's supposed to protect against.

I was thinking that it would stop the discord app from scanning programs on the system at all. Along with any client side analytics (Im not a programmer by any means but the plugin.js seems to do this?).

 I don't really know how to tell for sure if analytics are disabled but I can tell for sure that Discord is still able to tell me what app i have open in the background though

Does this plugin still work? Or am I might be misunderstanding the intentions of the plugin

**Comment by PreciousWarrior** [comment] 2021-04-06 07:37
I think it's broken, I realized pings were still being sent to sentry servers even though the plugin was enabled, and there was an error in startup on the console. Commenting out `electron.remote.getCurrentWebContents().removeAllListeners("devtools-opened"); // Remove dumb console warning` seems to fix it for now, but there are still errors caused by the plugin, and I don't know if it's functioning properly. Guess it needs to be rewritten because of Discord changes.

**Comment by rauenzi** [comment] 2021-04-17 21:30
Duplicate of #352

**Closed by rauenzi** 2021-04-17 21:30 UTC
