### ISSUE TITLE
[Bug] StatusEverywhere - Broken display

### ISSUE THREAD

**Issue by Glaived** [rauenzi/BetterDiscordAddons#230] opened 2020-05-06 03:50 UTC
**Which plugin/theme is this about?**
StatusEverywhere

**Describe the Bug**
Broken display

**To Reproduce**

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1835170/81137013-7b34a680-8f5d-11ea-8ead-309da58fa1ee.png)

**Discord Version**
Stable

**Additional Context**

**Comment by orblazer** [comment] 2020-05-06 07:46
That its caused by the class `wrapper-3t9DeA` on the avatar div. I search how i can fix that

**Comment by EnderBro123** [comment] 2020-05-06 15:05
Sane issue.

**Comment by Huddlect** [comment] 2020-05-06 20:23
d5a2440 fixed the issue for me.

**Comment by rauenzi** [comment] 2020-05-06 20:24
Yup forgot to close the issues.

**Closed by rauenzi** 2020-05-06 20:24 UTC
Labels: bug
