### ISSUE TITLE
[Bug] [EmojiUtilities] No Context Menu

### ISSUE THREAD

**Issue by McCovican** [rauenzi/BetterDiscordAddons#154] opened 2019-08-21 07:53 UTC
**Which plugin/theme is this about?**
EmojiUtilities

**Describe the Bug**
Context menu in emoji picker doesn't show up at all, meaning you can no longer add/remove favourite emojis.

**To Reproduce**
No special considerations.

**Expected Behavior**
Right clicking on an emoji should have the option to favourite/blacklist an emoji (or remove it from the favourite/blacklist sections)

**Screenshots**
N/A

**Discord Version**
Stable

**Additional Context**
N/A

**Comment by pie-flavor** [comment] 2019-09-25 05:58
Seconded

**Comment by rauenzi** [comment] 2019-09-25 06:00
@pie-flavor the same comment I made in the other issue applies to all issues--comme ts like this do not help. Please refrain from it in the future.

**Comment by rauenzi** [comment] 2020-03-04 01:01
Duplicate of #212
Since the plugin is totally broken, going to mark as duplicate and consolidate everything there.

**Closed by rauenzi** 2020-03-04 01:01 UTC
Labels: bug, confirmed
