### ISSUE TITLE
[Bug] RoleMembers not working

### ISSUE THREAD

**Issue by jack652** [rauenzi/BetterDiscordAddons#473] opened 2021-09-27 19:29 UTC
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
when clicking on a role mention, or on a role via the context menu when right clicking on the server, nothing happens

**To Reproduce**
click on a role mention or on a role via the context menu when right clicking on the server

**Expected Behavior**
a menu showing who has the selected role should appear

**Discord Version**
stable 99031 (720b494)
BetterDiscord 1.2.1
Host 1.0.9003

**Comment by rauenzi** [comment] 2021-09-27 19:30
You already commented on an existing issue for the same problem, why open a new one? duplicate of #462

**Closed by rauenzi** 2021-09-27 19:30 UTC
Labels: bug
