### ISSUE TITLE
Bot Images

### ISSUE THREAD

**Issue by delolione** [rauenzi/BetterDiscordAddons#68] opened 2018-08-24 21:46 UTC
If someone uses a bot to post NSFW images. Those images will not be blurred.

**Comment by rauenzi** [comment] 2018-08-24 22:20
It blurs images in channels marked NSFW not based on the image content

**Comment by intrnl** [comment] 2018-08-24 23:15
The issue is vague anyway, it doesn't tell if it was in an NSFW channel or not.

**Comment by rauenzi** [comment] 2018-08-27 15:27
I am closing this until further information comes forward.

**Closed by rauenzi** 2018-08-27 15:27 UTC
