### ISSUE TITLE
[Bug] RoleMembers menu not opening when trying to access it via a role mention

### ISSUE THREAD

**Issue by Mystixs3** [rauenzi/BetterDiscordAddons#382] opened 2021-04-26 16:40 UTC
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
When trying to see the role members menu using the role mention it doesn't appear

**To Reproduce**
Click on a mention and it doesn't appear.

**Expected Behavior**
When I click on the role mention I expect the role members menu to open and show me all the members in that role.

**Discord Version**
Canary 83062 (5f53310) & BetterDiscord 1.1.0

**Additional Context**
Also I've tried it without any other plugins and it still happens.
Other than that the plugin works fine.

**Comment by rauenzi** [comment] 2021-05-06 23:57
Duplicate of #281

**Closed by rauenzi** 2021-05-06 23:57 UTC
Labels: bug
