### ISSUE TITLE
[Bug][EmojiUtilities] Reactions Invisible

### ISSUE THREAD

**Issue by McCovican** [rauenzi/BetterDiscordAddons#204] opened 2020-02-05 17:44 UTC
Howdy,

Since the most recent update, EmojiUtilities results in message reactions being hidden entirely. You can still *add* reactions, and view existing ones via the native right-click menu. However, they are not shown inline anymore. This is not a stylesheet issue, as reactions are removed from the DOM entirely when this plugin is enabled. Disabling the plugin and switching channels/reloading the client will result in them becoming visible again immediately.

![200205174320](https://user-images.githubusercontent.com/11760565/73867733-14f59600-483f-11ea-93f6-1df0cc1c2a60.png)

**Comment by rauenzi** [comment] 2020-02-09 20:25
Yes that is correct, please disable EmojiUtilities for now

**Comment by rauenzi** [comment] 2020-03-04 00:59
Since the plugin is totally broken, going to mark duplicate of #212 and consolidate everything there.

**Closed by rauenzi** 2020-03-04 00:59 UTC
Labels: bug
